def html = """
<h1>Название страницы</h1>
<ac:structured-macro ac:name="mermaid">
  <ac:plain-text-body><![CDATA[
  graph TD
    A[Начало] --> B[Процесс]
    B --> C[Конец]
  ]]></ac:plain-text-body>
</ac:structured-macro>
"""
def chartData = [
    ["Янв", 100, 120],
    ["Фев", 110, 130],
    ["Мар", 120, 140],
    ["Апр", 130, 150]
]

// Формирование HTML с макросом диаграммы
def html = """
<ac:structured-macro ac:name="chart-from-table">
  <ac:parameter ac:name="type">line</ac:parameter>
  <ac:rich-text-body>
    <table>
      <tbody>
        <tr>
          <th>Месяц</th>
          <th>Продажи 2023</th>
          <th>Продажи 2024</th>
        </tr>
        ${chartData.collect { row ->
          "<tr>${row.collect { cell -> "<td>${cell}</td>" }.join("")}</tr>"
        }.join("")}
      </tbody>
    </table>
  </ac:rich-text-body>
</ac:structured-macro>
"""
<table class="wysiwyg-macro" data-macro-name="table-chart" data-macro-id="some-unique-id" data-macro-parameters="type=line" data-macro-schema-version="1" data-macro-body-type="RICH_TEXT">
  <tbody>
    <tr>
      <td class="wysiwyg-macro-body">
        <table>
          <tbody>
            <tr>
              <th>Месяц</th>
              <th>Продажи 2023</th>
              <th>Продажи 2024</th>
            </tr>
            ${chartData.collect { row ->
              "<tr>${row.collect { cell -> "<td>${cell}</td>" }.join("")}</tr>"
            }.join("")}
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
