def generateASClusterChart(Map totalAS, Map testAS, Map prodAS) {
    def allClusters = (totalAS.keySet() + testAS.keySet() + prodAS.keySet()).unique().sort()
    
    // Генерация содержимого таблицы
    def tableContent = new StringBuilder()
    tableContent.append("<tr><th>Кластер</th><th>Цель</th><th>IFT</th><th>П</th></tr>")
    allClusters.each { cluster ->
        tableContent.append("<tr>")
        tableContent.append("<td>${cluster}</td>")
        tableContent.append("<td>${totalAS.getOrDefault(cluster, 0)}</td>")
        tableContent.append("<td>${testAS.getOrDefault(cluster, 0)}</td>")
        tableContent.append("<td>${prodAS.getOrDefault(cluster, 0)}</td>")
        tableContent.append("</tr>")
    }
    
    // Формирование HTML с макросом "Диаграмма из таблицы"
    def html = """
    <ac:structured-macro ac:name="chart-from-table">
        <ac:parameter ac:name="type">column</ac:parameter>
        <ac:parameter ac:name="title">Количество  по кластерам</ac:parameter>
        <ac:parameter ac:name="width">100%</ac:parameter>
        <ac:parameter ac:name="height">500</ac:parameter>
        <ac:parameter ac:name="is3d">true</ac:parameter>
        <ac:parameter ac:name="legend-position">right</ac:parameter>
        <ac:parameter ac:name="hide-data">true</ac:parameter>
        <ac:parameter ac:name="align">center</ac:parameter>
        <ac:rich-text-body>
            <table>
                <tbody>
                    ${tableContent}
                </tbody>
            </table>
        </ac:rich-text-body>
    </ac:structured-macro>
    """
    
    return html
}


 def renameEmptyKey = { map ->
        if (map.containsKey("")) {
            def value = map.remove("")
            map.put("Без кластера", value)
        }
        return map
    }

    // Переименовываем пустые ключи во всех мапах
    totalAS = renameEmptyKey(totalAS)
    testAS = renameEmptyKey(testAS)
    prodAS = renameEmptyKey(prodAS)
