def chartData = [
    ["Category A", 30],
    ["Category B", 50],
    ["Category C", 20]
]

// Формирование HTML с макросом диаграммы и встроенной таблицей данных
def html = """
<ac:structured-macro ac:name="chart">
  <ac:parameter ac:name="type">pie</ac:parameter>
  <ac:parameter ac:name="title">Sample Chart</ac:parameter>
  <ac:parameter ac:name="width">500</ac:parameter>
  <ac:parameter ac:name="height">300</ac:parameter>
  <ac:parameter ac:name="dataDisplay">percentage</ac:parameter>
  <ac:rich-text-body>
    <table>
      <tbody>
        <tr>
          <th>Category</th>
          <th>Value</th>
        </tr>
        ${chartData.collect { row ->
          "<tr><td>${row[0]}</td><td>${row[1]}</td></tr>"
        }.join("")}
      </tbody>
    </table>
  </ac:rich-text-body>
</ac:structured-macro>
